version: '3'
services:
  app:
    container_name: latian-nestjs-app
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: yarn start:dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: latian-nestjs-pg
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env

volumes:
  pgdata:
